### ISSUE TITLE
Make vscode-epsilon a valid web extension

### ISSUE THREAD

**Issue by kolovos** [Arkaedan/vscode-epsilon#3]
As the extension now provides a `main` entry point but not a `browser` one, it is not a valid [web extension](https://code.visualstudio.com/api/extension-guides/web-extensions#web-extension-anatomy) and therefore it cannot be installed on web-based instances of VS Code (e.g. on github.dev).

Adding an extra `"browser": "./out/extension.js"` line to package.json *should* work as I can't see anything in the location detection code that shouldn't work in the browser, but I haven't tried it. If that fails, it may be worth pointing `browser` to a skeleton entrypoint until a better solution is found.

**Comment by Arkaedan** [comment]
Thanks @kolovos I have published this change in version 1.2.1. I have just checked and it is showing as available to install in the web version.
