### ISSUE TITLE
Publish extension to OpenVSX

### ISSUE THREAD

**Issue by kolovos** [Arkaedan/vscode-epsilon#6]
It would be nice to also publish the extension to [OpenVSX](https://open-vsx.org/) so that it can be installed in other VS-Code-compatible environments, such as Eclipse Theia, too.

**Comment by Arkaedan** [comment]
I have now setup automated publishing to both VS Marketplace and OpenVSX.

Link to extension on Open VSX: https://open-vsx.org/extension/SamHarris/eclipse-epsilon-languages
